{{- if .Values.crd.install }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "renovate-operator.fullname" . }}-crd-hook
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "-5"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "renovate-operator.fullname" . }}-crd-hook
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "-5"
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "renovate-operator.fullname" . }}-crd-hook
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "-5"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "renovate-operator.fullname" . }}-crd-hook
subjects:
  - kind: ServiceAccount
    name: {{ include "renovate-operator.fullname" . }}-crd-hook
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "renovate-operator.fullname" . }}-crd
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "-5"
data:
  renovatejob.yaml: |
{{ .Files.Get "crd/renovate-operator.mogenius.com_renovatejobs.yaml" | indent 4 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "renovate-operator.fullname" . }}-crd-install
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "0"
spec:
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: {{ include "renovate-operator.fullname" . }}-crd-hook
      restartPolicy: OnFailure
      {{- with .Values.crd.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: kubectl
          {{- with .Values.crd.image }}
          image: {{ .registry }}/{{ .repository }}:{{ .tag }}
          imagePullPolicy: {{ .pullPolicy }}
          {{- end }}
          command:
            - kubectl
            - apply
            - -f
            - /crd/renovatejob.yaml
          volumeMounts:
            - name: crd
              mountPath: /crd
      volumes:
        - name: crd
          configMap:
            name: {{ include "renovate-operator.fullname" . }}-crd
{{- end }}
