{{- if and .Values.crd.install (eq .Values.crd.mode "template") }}
{{- $currentScope := . }}
{{- range $path, $_ := .Files.Glob "crd/**" }}
  {{- with $currentScope }}
    {{- .Files.Get $path }}
  {{- end }}
{{- end }}
{{- end }}
