{{- if not .Values.rbac.ownNamespaceOnly }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "renovate-operator.fullname" . }}
rules:
  # Allow get, list, update on renovatejobs
  - apiGroups: ["renovate-operator.mogenius.com"]
    resources: ["renovatejobs", "renovatejobs/status"]
    verbs: ["get", "list", "watch", "update", "patch"]

  # Allow create, get, list, update, delete on pods
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]

  # Allow create, get, list, update, delete on jobs
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]

  # Allow log access from pods
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]

  # Allow reading secrets for webhook token and github app integration
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]

  {{- if gt (int .Values.replicaCount) 1 }}
  # Allow leader election via coordination leases
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["create", "get", "update"]
  {{- end }}
{{- end }}
